# Generated by Django 5.2.6 on 2025-09-11 21:02

import django.db.models.deletion
import submissions.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Evaluation'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('file1', models.FileField(upload_to=submissions.models.Submission.get_upload_path)),
                ('file2', models.FileField(upload_to=submissions.models.Submission.get_upload_path)),
                ('file3', models.FileField(upload_to=submissions.models.Submission.get_upload_path)),
                ('file4', models.FileField(upload_to=submissions.models.Submission.get_upload_path)),
                ('file5', models.FileField(upload_to=submissions.models.Submission.get_upload_path)),
                ('file6', models.FileField(upload_to=submissions.models.Submission.get_upload_path)),
                ('file7', models.FileField(upload_to=submissions.models.Submission.get_upload_path)),
                ('file8', models.FileField(blank=True, null=True, upload_to=submissions.models.Submission.get_upload_path)),
                ('file9', models.FileField(blank=True, null=True, upload_to=submissions.models.Submission.get_upload_path)),
                ('is_disqualified', models.BooleanField(default=False, help_text='Check this to hide the submission from the leaderboard and visualization.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('grid_costs', models.FloatField(default=0.0)),
                ('renewables_installed', models.FloatField(default=0.0)),
                ('autarchy_rate', models.FloatField(default=0.0)),
                ('details', models.JSONField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='submissions.submission')),
            ],
            options={
                'ordering': ['submission', 'station_name'],
                'unique_together': {('submission', 'station_name')},
            },
        ),
    ]
