# Generated by Django 5.2.6 on 2025-09-07 12:30

import django.db.models.deletion
import submissions.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Evaluation'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('file1', models.FileField(upload_to=submissions.models.Submission.get_upload_path)),
                ('file2', models.FileField(upload_to=submissions.models.Submission.get_upload_path)),
                ('file3', models.FileField(upload_to=submissions.models.Submission.get_upload_path)),
                ('file4', models.FileField(upload_to=submissions.models.Submission.get_upload_path)),
                ('file5', models.FileField(upload_to=submissions.models.Submission.get_upload_path)),
                ('file6', models.FileField(upload_to=submissions.models.Submission.get_upload_path)),
                ('file7', models.FileField(upload_to=submissions.models.Submission.get_upload_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='submissions.submission')),
                ('score', models.FloatField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
