# Generated by Django 5.2.6 on 2025-09-07 14:53

import submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='file8',
            field=models.FileField(blank=True, null=True, upload_to=submissions.models.Submission.get_upload_path),
        ),
        migrations.AddField(
            model_name='submission',
            name='file9',
            field=models.FileField(blank=True, null=True, upload_to=submissions.models.Submission.get_upload_path),
        ),
    ]
