# Generated by Django 5.2.6 on 2025-09-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_file8_submission_file9'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationresult',
            name='score',
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='score_objective_1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='score_objective_2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='score_objective_3',
            field=models.FloatField(default=0.0),
        ),
    ]
