# Generated by Django 5.2.6 on 2025-09-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_remove_evaluationresult_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_disqualified',
            field=models.BooleanField(default=False, help_text='Check this to hide the submission from the leaderboard and visualization.'),
        ),
    ]
