# Generated by Django 5.2.6 on 2025-09-07 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_submission_is_disqualified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationresult',
            old_name='score_objective_1',
            new_name='autarchy_rate',
        ),
        migrations.RenameField(
            model_name='evaluationresult',
            old_name='score_objective_2',
            new_name='grid_costs',
        ),
        migrations.RenameField(
            model_name='evaluationresult',
            old_name='score_objective_3',
            new_name='renewables_installed',
        ),
    ]
